package tests;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import pages.Driver;
import pages.GoToLoginPage;
import pages.LoginPage;


public class TestTask7 {
    @BeforeClass
    public static void startDriver() {
        new GoToLoginPage().getpage();

    }

    @Test
    public void test() throws InterruptedException {
        new LoginPage()
                .inputLoginAndPassword()
                .goToAppearencePage()
                .checkHeadingPage()
                .returnMainPage()
                .goToLogotypePage()
                .checkHeadingLogotypePage()
                .returnMainPage()
                .goToCatalogPage()
                .checkHeadingCatalogPage()
                .goToProductGroupsPage()
                .checkHeadingProductGroupsPage()
                .returnCatalogPage()
                .goToOptionGroupsPage()
                .checkHeadingOptionGroupsPage()
                .returnCatalogPage()
                .goToManufacturersPage()
                .checkHeadingManufacturerPage()
                .returnCatalogPage()
                .goToSuppliersPage()
                .checkHeadingSuppliersPage()
                .returnCatalogPage()
                .goToDeliveryStatusesPage()
                .checkHeadingDeliveryStatusesPage()
                .returnCatalogPage()
                .goToSoldOutStatusesPage()
                .checkHeadingSoldOutStatusesPage()
                .returnCatalogPage()
                .goToQuantityUnitsPage()
                .checkHeadingQuantityUnitsPage()
                .returnCatalogPage()
                .goToCSVImportExportPage()
                .checkHeadingCSVImportExportPage()
                .returnCatalogPage()
                .returnMainPage()
                .goToCountriesPage()
                .checkHeadingCountriesPage()
                .returnMainPage()
                .goToCurrenciesPage()
                .checkHeadingCountriesPage()
                .returnMainPage()
                .goToCustomersPage()
                .checkHeadingCustomersPage()
                .goToCustomersCSVImportExportPage()
                .checkHeadingCustomersCSVImportExportPage()
                .returnCustomersPage()
                .goToNewsletterPage()
                .checkHeadingCustomersCSVImportExportPage()
                .returnMainPage()
                .goToGeoZonesPage()
                .checkHeadingGeoZonesPage()
                .returnMainPage()
                .goToLanguagesPage()
                .checkHeadingLanguagesPage()
                .goToStorageEncodingPage()
                .checkHeadingStorageEncodingPage()
                .returnLanguagesPage()
                .returnMainPage()
                .goToModulesPage()
                .checkHeadingModulesPage()
                .goToModulesCustomerPage()
                .checkHeadingModulesPage()
                .returnModulesPage()
                .goToShippingPage()
                .checkHeadingModulesPage()
                .returnModulesPage()
                .goToPaymentPage()
                .checkHeadingPaymentPage()
                .returnModulesPage()
                .goToOrderTotalPage()
                .checkHeadingOrderTotalPage()
                .returnModulesPage()
                .goToOrderSuccessPage()
                .checkHeadingOrderSuccessPage()
                .returnModulesPage()
                .goToOrderActionPage()
                .checkHeadingOrderActionPage()
                .returnModulesPage()
                .returnMainPage()
                .goToOrdersPage()
                .checkHeadingOrdersPage()
                .goToOrderStatusesPage()
                .checkHeadingOrderStatusesPage()
                .returnMainPage()
                .goToPages()
                .checkHeadingPages()
                .returnMainPage()
                .goToReportsPages()
                .checkHeadingReportsPages()
                .goToMostSoldProductsPage()
                .checkHeadingMostSoldProductsPage()
                .returnReportsPages()
                .goToMostShoppingCustomersPage()
                .checkHeadingMostShoppingCustomersPage()
                .returnReportsPages()
                .returnMainPage()
                .goToSettingsPage()
                .checkHeadingSettingsPage()
                .goToDefaultsPage()
                .checkHeadingDefaultsPage()
                .returnSettingsPage()
                .goToDGeneralPage()
                .checkHeadingGeneralPage()
                .returnSettingsPage()
                .goToListingsPage()
                .checkHeadingListingsPage()
                .returnSettingsPage()
                .goToImagesPage()
                .checkHeadingImagesPage()
                .returnSettingsPage()
                .goToCheckoutPage()
                .checkHeadingImagesPage()
                .returnSettingsPage()
                .goToAdvancedPage()
                .checkHeadingAdvancedPage()
                .returnSettingsPage()
                .goToSecurityPage()
                .checkHeadingSecurityPage()
                .returnSettingsPage()
                .returnMainPage()
                .goToSlidesPage()
                .checkHeadingSlidesPage()
                .returnMainPage()
                .goToTaxPage()
                .checkHeadingTaxPage()
                .goToTaxRatesPage()
                .checkHeadingTaxRatesPage()
                .returnTaxPage()
                .returnMainPage()
                .goToTranslationsPage()
                .checkHeadingTranslationsPage()
                .goToScanFilesPage()
                .checkHeadingScanFilesPage()
                .returnTranslationsPage()
                .goToTranslationsCSVImportExportPage()
                .checkHeadingScanFilesPage()
                .returnTranslationsPage()
                .returnMainPage()
                .goToScanUsersPage()
                .checkHeadingUsersPage()
                .returnMainPage()
                .goToVQmodsPage()
                .checkHeadingVQmodsPage();


    }

    @AfterClass
    public static void stopDriver() {
        Driver.stopDriver();

    }

}